### ISSUE TITLE
Weights of the stage one

### ISSUE THREAD

**Issue by Aziily** [MooreThreads/Moore-AnimateAnyone#38]
Hello, thanks for your open weights. However, I am wondering to use some features of the result from the first training stage, will you share these weights?
I also wondering the ability of keeping id and generating high-quality image about the first-stage result, would you share me with this experience?

**Comment by lixunsong** [comment]
The current released weights include stage1 training results, because `reference_unet`, `deonising_unet` and `pose_guider` weights are frozen in stage2 training. We are about to release our training code and will also share the experience.

**Comment by Aziily** [comment]
Thanks for your explanation, I figure out that the stage 2 only modifies the motion module and can prohibit it from being used. Waiting for your experience. Thanks a lot.

**Comment by Aziily** [comment]
Hello, sorry for disturbing again, but I meet a problem when trying to use the ref only pipe for image generation. When I use this choice in config, I still face the problem seems resulted by temporal modules. For example, the video seems to have some mosaic parts which is blurred, but if I set length of video to 1 and sample frames one by one, the quality is great. Below is my config.
```yaml
unet_additional_kwargs:
  use_inflated_groupnorm: false
  unet_use_cross_frame_attention: false 
  unet_use_temporal_attention: false
  use_motion_module: false
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: true 
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div: 1

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  clip_sample: false
  steps_offset: 1
  ### Zero-SNR params
  prediction_type: "v_prediction"
  rescale_betas_zero_snr: True
  timestep_spacing: "trailing"

sampler: DDIM 
```
As far as I am concerned, the motion module is responsible for the temporal module, so if I set this to `false`, then every frame of a video should just be sampled as one by one? However, the result is different. I am wondering whether there are some other settings required to be changed, or can you offer a pipeline or some reference for pose2img? Since the denoising unet is trained on Unet2D Model, totally exclude the temporal model is possible?
